### ISSUE TITLE
What are our deliverables?

### ISSUE THREAD

**Issue by jonathanrobie** [usfm-bible/tcdocs#1]
We need to figure out who is doing what ... and some of that starts with "what".  What are our deliverables?   I suspect we need at least:

- A revised USFM specification
    - Include fixes people have asked for and others that come up
    - Be more explicit about hierarchy
    - Include a formal grammar
    - Define the transformation from USFM to USX
 - A reference implementation
 - A test suite

In order to finish, I think we should want two independent implementations that report the same results on the test suite.

What do the rest of you think?  What do we need to deliver to be able to say we have done our job well?  We should also be thinking about who would be willing to do what.

**Comment by jonathanrobie** [comment]
John Lambert found that the USFM parser we are using fails to parse about 10% of existing DBL resources.  We need a plan for handling existing resources that do not parse with a formal definition - do we need both a "strict" and a "lax" definition?  If so, how do we prevent the "strict" from becoming irrelevant?

**Comment by jonathanrobie** [comment]
Do we need marketing deliverables such as Wikipedia entries?

**Comment by klassenjm** [comment]
@jonathanrobie You mention a USFM parser failing to parse DBL resources. Are you referring to resources gathered from DBL by Paratext? If so, yes - they would be seen on a system in Paratext as USFM, and they are stored in a p8z file. For any client other than Paratext, DBL entries are delivered in USX, and those USX files *did* validate with the USX schema.

My comments here I suppose are an effort to clarify what process is occurring on John Lambert's end.

**Comment by jonathanrobie** [comment]
Thanks, Jeff.

So the obvious thing to do is extract the USX instead of the USFM from
these files.   Let's discuss that offline ...

Jonathan

**Comment by mhosken** [comment]
Our deliverables for 3.1 will be:

- Formal grammar (usx.rnc)
- Reference implementation (usfmconv)
- Test suite
- Documentation site including syntax diagrams

There are other deliverables we would like to add in due course

- scematron semantic tests
