### ISSUE TITLE
Can USX and USFM be improved to handle contexts?

### ISSUE THREAD

**Issue by KentSpiel** [usfm-bible/tcdocs#11]
One of my biggest bugaboos is the need to flatten text before publishing. The only way to properly style a text in HTML or IDML  is to  create all of the  styes that result from nesting. For example we commonly have Hebrew transliterated words in the Psalm  superscriptions: \d _xxx_  \tl _yyy_\tl*`  In publication yyy needs to be regular text, not italic. The need to transition between hierarchical/nested and flattened expressions of the USX should not be overlooked since the final goal of the format is not archiving but publication. 
* Perhaps there should be a limit on the amount of nesting allowed.
* Perhaps the USFM stylesheet should allow one to  specify the formatting of certain nested styles if they differ from a straight CSS stylesheet application e.g. : 
  * \tl in \d  
read _Transliterated Word embedded in Hebrew Subtitle._

A second concern is that context matters in formatting. For example: we always add extra vertical space when going from prose to poetry and then back again. 
* Perhaps the USFM stylesheet should allow one to  specify the formatting of certain styles based on context e.g. : 
  * \q1 following \p
  * \q1 following \m
  * \p following \q1
  * \p following \q2 
  * \m following \q1
  * \m following \q2

This could convert to USX with a context specific attribute. 

The desired result is improved formatting both in the PT editing environment and in print and electronic publications.

**Comment by mhosken** [comment]
This is out of scope for the standard. See how PTXprint handles this (at least hierarchically, rather than sequentially)
