### ISSUE TITLE
Best practice for marking internal links?

### ISSUE THREAD

**Issue by kahunapule** [usfm-bible/tcdocs#16]
The current demand by Paratext and the DBL to have all human-readable Scripture references conform to a computer-like syntax. While I understand that this is a nice attempt at maintaining backward compatibility with older texts, it also causes all kinds of errors with historical texts, demanding that history be changed or that the text be rejected. The new extension of an h-ref attribute to \xt markup provides a welcome reprieve from that problem, at a cost of breaking all old USFM readers, including mine. I can fix that, but I found another problem in that \xt ...\xt* seems to have taken on part of what \jmp ...\jmp* does, and \xt no longer seems to have anything to do with crossreference text. Right now, this is a confusing mess that I'm not sure what to do with...

**Comment by mhosken** [comment]
See \ref
