### ISSUE TITLE
Book Numbers - and NT numbering

### ISSUE THREAD

**Issue by jonathanrobie** [usfm-bible/tcdocs#3]
MARBLE and many other internal numbering systems use 40 to identify Matthew, e.g.

```xml
<MARBLELinks xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <MARBLELink Id="04000100100000">
    <ThematicLinks />
    <LexicalLinks />
    <TextualLinks />
    <ImageLinks>
      <ImageLink>tb042403039</ImageLink>
      <ImageLink>Genealogy_of_Jacob</ImageLink>
      <ImageLink>Genealogy-Jesus</ImageLink>
      <ImageLink>JesseTree</ImageLink>
      <ImageLink>AT Map00305</ImageLink>
    </ImageLinks>
    <MapLinks />
    <ArticleLinks />
    <SectionLinks>
      <SectionLink>GNSBUK001639</SectionLink>
    </SectionLinks>
  </MARBLELink>
  <MARBLELink Id="04000100100002">
    <ThematicLinks />
    <LexicalLinks>
      <LexicalLink>SDBG:βίβλος:000002:Communication</LexicalLink>
    </LexicalLinks>
    <TextualLinks />
```

But the USFM specification says the book code for Matthew is 041.   What is the intended use of that number?  Is anything broken here?

I am creating a lot of datasets that need to know whether to treat Matthew as 40 or 41 internally, so I'd like to know if this is an issue ...

**Comment by joelthe1** [comment]
I had asked a related question sometime back if that is helpful: https://github.com/ubsicap/usfm/issues/99

**Comment by jwickberg** [comment]
I think the only place that MAT = 41 is used in Paratext is in the file name of the book text.

The versification code we use from the LibPalaso library has MAT = 40

I don't know of any where in USFM/USX where book number is used.

**Comment by mhosken** [comment]
Ptxprint follows paratect in using 41. This is a potential mess. We need to
agree and implement. I don't want to have to translate between them. If we
pick 40, that is going to cause quite a bit of pain, even if 40 is a better
answer.

I propose we use 41 until paratext can make the change. I don't see that
happening soon though. The cost of transition seems high to me.

Sigh.
GB,
Martin

**Comment by jonathanrobie** [comment]
Where does Paratext use 41?

**Comment by jwickberg** [comment]
I found 2 places looking in the Paratext code:
- the name of the USFM file for a book
- the name of the HTML file for a book when exporting a project as HTML

In both of these cases, all the numbers for NT books are shifted up 1.

**Comment by jonathanrobie** [comment]
So in the names of identifiers within a file, Matthew=40, in filenames,
Matthew=041, and that's fairly consistent in Paratext?

Jonathan

**Comment by jwickberg** [comment]
Except for the references you found in Marble data, references in Biblical Terms data, and book numbers in progress data (maybe a couple of others), the default is to use book id rather than book number. When book number is used internally, it has MAT=40.

The \id line and values for for parsed references in USX use the book id.

So, I think the only inconsistency is in file names where 41 was used for historical reasons.

**Comment by mhosken** [comment]
Thinking about this, I don't think it is in scope for USFM/USX. I think this is a scripture burrito question. I therefore propose closing this issue once someone has transferred it to that project. Please could whoever does the transfer, respond or close this issue.

**Comment by jonathanrobie** [comment]
I don't think it SHOULD be in scope for USFM/USX, but it is, because our
spec currently seems to define it here:

https://ubsicap.github.io/usfm/identification/books.html

In that table, does the NUMBER column have a normative meaning?  If so,
what is that meaning?  The only definition given is this:

Some scripture editors like Paratext <http://paratext.org/> may also
> include the number shown for each book in the filename for that book.


But it doesn't say, for instance, that Paratext uses different numbers
internally, and doesn't even mention the numbering scheme used by Paratext
and MARBLE.   I think we're slightly pregnant here, we need to get to a
consistent state.

**Comment by mhosken** [comment]
I propose we don't carry that numbering forward, declare it non-normative and turf it over the wall to scripture burrito :) Those numbers never occur in USFM/USX data (he says, oh so confidently) so can only be informative if listed in the current docs.

**Comment by mhosken** [comment]
I propose we don't carry that numbering forward, declare it non-normative and turf it over the wall to scripture burrito :) Those numbers never occur in USFM/USX data (he says, oh so confidently) so can only be informative if listed in the current docs.

**Comment by KentSpiel** [comment]
From the Biblica perspective, we use the numbers one through 66 and remember all of our files beginning with Matthew to start with 40. Since the point of our current mission is to document the current state of USFM/US, I propose that we include the current numbering system. At the same time, I propose we also approve any numbering system that includes a  2-digit number and a 3-letter book code.

**Comment by jonathanrobie** [comment]
Joel and I were asked to talk to the Scripture Burrito working group about book numbers and other metadata that spans individual USFM files.

We need to define these things in Scripture Burrito, and have already defined ways to declare book order, including multiple orders, using ordered lists (https://docs.burrito.bible/en/latest/schema_docs/scope.html). This means that the same content can be published in multiple orders, e.g. in a Catholic edition, an Orthodox edition, and a Protestant edition. We do not use book numbers for this.  We do not believe they are necessary.   Different agencies use 40 or 41 for Matthew, but this does not cause any real interoperability problems.  After all, they also spell Matthew differently, depending on the language.  40-Matthew or 41-Matthias are both valid.

Scripture Burrito is an exchange format, not a persistent file format, though there is no technical barrier for an application that wants to use it that way. We are happy to have applications use Scripture Burrito to specify metadata for a set of files anywhere they need to.
