### ISSUE TITLE
User defined attributes - "may"?

### ISSUE THREAD

**Issue by jonathanrobie** [usfm-bible/tcdocs#59]
https://docs.usfm.bible/usfm-usx-docs/latest/char/attributes.html#_user_defined_attributes

> Using the general syntax above, attributes may be added to any character markers beyond the formalized set in the current version of the USFM/USX specification. These will not be considered strictly canonical, and software supporting USFM/USX may not process user-deined attributes. (Future versions of USFM may formally provide additional attributes within the specification.)

What does "may not process" mean here?  

1. Software must not, or
2. Software is not required to

**Comment by mhosken** [comment]
Now I see the ambiguity. Here it means "is not required to".
