### ISSUE TITLE
Move \em from Character Styling to Special Text 

### ISSUE THREAD

**Issue by KentSpiel** [usfm-bible/tcdocs#64]
The emphasized text marker does not inherently specify any particular format, therefore it should not be classified with the pure formatting markers:
*  \bd …\bd*
* \it …\it*
* \bdit …\bdit*
* \no …\no*
* \sc …\sc*
* \sup …\sup*

Move it under Special text.

**Comment by mhosken** [comment]
I'm not sure I agree with this. Can you strengthen your argument. Emphasis
is a styling even if it is not a concrete style.

**Comment by KentSpiel** [comment]
Not all scripts allow italic to represent emphasis:
In Sorani Kurdish \em is used in introductory material formatted \bold to provide a one paragraph summary of each book before more in depth introductory material.
![image](https://github.com/usfm-bible/tcdocs/assets/6817239/bc9c5272-83f5-4ae2-916c-30996dcbcdca)
I recommended that they use \em rather than \bd for this because that is the style they wanted. Italic is not an option fro emphasis n Arabic scripts so some other formatting option is necessary. 
Another example:
We use \em in our Danish translation  Bibelen på hverdagsdansk (The Bible in Everyday Danish) in both the introductory material and in the main text. It is formatted as italic. In this case w also are using \bd for in-lline heading.
![image](https://github.com/usfm-bible/tcdocs/assets/6817239/ea38f32f-0f28-4610-9b6e-6967195bef5d)

**Comment by mhosken** [comment]
Yes \em is kind of unique in that the other styles in that group are concrete, rather than semantic. But grouping is about parsing behaviour more than styling that it is hard to justify creating a new subcategory just for this. So after discussion, we have decided to take no action on this
