### ISSUE TITLE
Milestone diagram includes char marker `fp`

### ISSUE THREAD

**Issue by irahopkinson** [usfm-bible/tcdocs#68]
Both the USFM and USX diagrams for a milestone include the char footnote marker `fp`, see https://docs.usfm.bible/usfm-usx-docs/latest/ms/index.html.

I'm pretty sure that needs to be removed from both.

I'm not sure how to update a diagram otherwise I'd make a PR.

**Comment by mhosken** [comment]
\fp joins a small elite set of markers that should take no data, including \b. These are in effect milestones that trigger a paragraph break. For now I think the best approach here is to treat \fp as if it were a special \ft that triggers a paragraph break in the note. Of course that raises the question for typesetters as to what a paragraph break means in a sequence of notes that are paragraphed into a single paragraph.

I have moved \fp back to being a footnote character. BTW to make such a change, on edits grammar/usx.rnc and then runs make to regenerate the diagrams.
