### ISSUE TITLE
Confusing documentation of attributes

### ISSUE THREAD

**Issue by chrisvire** [usfm-bible/tcdocs#71]
Comparing the documentation for `\fig` in 3.0:
https://ubsicap.github.io/usfm/characters/index.html#fig-fig

to the new documentation for `\fig`:
https://docs.usfm.bible/usfm-usx-docs/latest/fig/fig.html

1. The new documentation has confusing `@attribute` stuff. For someone new to USFM, what are they supposed to do?

![image](https://github.com/usfm-bible/tcdocs/assets/517814/8c7937f9-4755-431b-9143-ed3f9cdeab06)

2. There is no explanation about required vs. optional attributes.  In the old documentation, there was a statement:

> Required attributes are indicated in the list below with a red asterisk *.

This is missing from the new documentation. There are asterisks after the attribute names, but no explanation that it means they are required. I actually missed the fact that they were there until someone pointed them out.

**Comment by chrisvire** [comment]
Any comments?

**Comment by KentSpiel** [comment]
I think the `content | @attr` syntax should me mentioned here:
https://docs.usfm.bible/usfm-usx-docs/latest/char/attributes.html along with how required and optional attributes are marked.  I would also suggest that we put an asterisk after the required attrs as well as the descriptions. If the asterisks can be linked to a footnote or go to an explanatory page that would be even beter:

 - **USFM:** `\fig caption|@src* @size* @ref @alt @loc @copy\fig*`

 - **USX:** `<figure style="fig" @file* @size* @ref @alt @loc @copy>caption</figure>`

#### src* (USFM) / file* (USX) 
  Filename

#### size*

 Illustration relative size. Options are col (illustration should be inserted inline within the current text column) or span (illustration should be inserted across – 'spanning' – text columns).

**Comment by klassenjm** [comment]
@chrisvire Thanks for reviewing and comparing the documentation (old and new), and sharing this feedback. I've been working on the new documents -- endeavoring to harmonize the USFM, USX, and USJ (at least USJ examples). It's been slow to get to completion recently -- just due to other work. I can take your feedback and Kent's suggestions (thanks @KentSpiel) and work at some improvements. I understand your points, and I'll try to get back to this soon.

**Comment by klassenjm** [comment]
Updates:
- There is a new [documentation syntax](https://docs.usfm.bible/usfm-usx-docs/latest/syntax-docs.html) page in the introduction.
- The Introduction section sub-pages are shown on the landing page (i.e. the reader would see sooner that this background info exists)
- On every page where there is a markup description, the 'Syntax' heading links to the [documentation syntax](https://docs.usfm.bible/usfm-usx-docs/latest/syntax-docs.html) page, as a help.

**Comment by klassenjm** [comment]
Hopefully this improves the experience for a reader.
