### ISSUE TITLE
ChapterContent missing description of Figure

### ISSUE THREAD

**Issue by chrisvire** [usfm-bible/tcdocs#73]
On https://docs.usfm.bible/usfm-usx-docs/latest/doc/index.html#doc-book-chapter-content, there is a picture of the grammar which includes `Figure`:

![image](https://github.com/usfm-bible/tcdocs/assets/517814/da4efb3b-b85b-4998-8cb5-85e55717aaff)

But the description of the sections below that has all the elements in the picture except for `Figure`.

**Comment by jwickberg** [comment]
Figure will be removed from this level - it will remain as paragraph content.

Paragraph content is shown on this page: https://docs.usfm.bible/usfm-usx-docs/latest/para/index.html
