### ISSUE TITLE
Must \v always be preceded by a space?

### ISSUE THREAD

**Issue by KentSpiel** [usfm-bible/tcdocs#9]
Current Normalized or canonical USFM requires \v start on a new line. If the  \v is preceded by text, this means a space is always displayed before the verse number and when  converted to USX the preceding text span ends with a space. This is not always desired. I have several hundred examples in my data. The following is common markup for the doubtful verse ACT 8:37:
<sup>36</sup> Text1 [<sup>37</sup> Text2] becomes in standardized/normalized USFM:
`\v 36 Text1 [`
`\v 37 Text2]`
which then gets exported in USX with a space before  \v 37
`<verse number="36" style="v" sid="ACT 8:36" />Text1 [ <verse eid="ACT 8:36" /><verse number="37" style="v" sid="ACT 8:37" />Text2]<verse eid="ACT 8:37" />`

I propose that  \v is not required to be on a new line in normalized USFM
OR
A  verse style marker be defined to include any preceding new line/line feed characters: `[\r\n]*\\v\s`, which will not be converted into a space in USX.

**Comment by mhosken** [comment]
I agree. This is less an issue for the description of USFM, where the \n (acting as a space) is part of the preceding Text, so much as requiring USX to have <Para>, <Char> and <Note> elements to be space preserving.

**Comment by KentSpiel** [comment]
The current definition of \\v now states that it does not need to start on a new line. If it does start on a new line in a particular application (i.e. Paratext) It follows the normal rules of canonicalization, any preceding whitespace (_WS_) is  reduced to zero. An application is misbehaving if it inserts a _nl_ between _TEXT_ and  \\v .Paratext is currently misbehaving except when the preceding TEXT ends with  `( ` or `[`.

**Comment by mhosken** [comment]
There is now a difference between accepted and canonical, but even then a space shouldn't be required before a \v
